import LegalPage, { L, co, legalMetadata, pending } from "@/components/LegalPage";
import { GamesRtpTable, OriginalsMaxWin, OriginalsRtpTable, PlinkoTablesLive } from "@/components/LegalLive";
import { RULES } from "@/lib/company";

export const metadata = legalMetadata("game-rules");

const nodeCheck = `const crypto = require("crypto");

const serverSeed = "...";  // revealed when you rotate the seed
const clientSeed = "...";  // your client seed for those bets
const nonce = 0;           // the bet's nonce

// 1. The revealed seed must match the hash shown before you bet
console.log(crypto.createHash("sha256").update(serverSeed).digest("hex"));

// 2. Recompute the roll
const h = crypto.createHmac("sha256", serverSeed).update(clientSeed + ":" + nonce).digest();
console.log(((h.readUInt32BE(0) % 10000) / 100).toFixed(2));`;

const pyCheck = `import hashlib, hmac

server_seed, client_seed, nonce = "...", "...", 0
print(hashlib.sha256(server_seed.encode()).hexdigest())
h = hmac.new(server_seed.encode(), f"{client_seed}:{nonce}".encode(), hashlib.sha256).digest()
print("%.2f" % (int.from_bytes(h[:4], "big") % 10000 / 100))`;

const nodeOriginals = `const crypto = require("crypto");
const hmac = (key, msg) => crypto.createHmac("sha256", key).update(msg).digest();
const serverSeed = "...", clientSeed = "...", nonce = 0;
const RTP = 99;            // the RTP the bet was played at, in percent (shown with the result)

// Crash point
const H = BigInt("0x" + hmac(serverSeed, clientSeed + ":" + nonce).toString("hex").slice(0, 13));
const E = 2n ** 52n;
let c = (BigInt(RTP) * E) / (E - H);
console.log("crash", Number(c < 100n ? 100n : c) / 100);

// Float stream for Mines and Plinko
function floats(n) {
  const out = [];
  for (let cursor = 0; out.length < n; cursor++) {
    const h = hmac(serverSeed, clientSeed + ":" + nonce + ":" + cursor);
    for (let i = 0; i < 32 && out.length < n; i += 4) out.push(h.readUInt32BE(i) / 2 ** 32);
  }
  return out;
}

// Mines (M mines)
const M = 3, tiles = [...Array(25).keys()], f = floats(24);
for (let k = 0, i = 24; i >= 1; k++, i--) { const j = Math.floor(f[k] * (i + 1)); [tiles[i], tiles[j]] = [tiles[j], tiles[i]]; }
console.log("mines", tiles.slice(0, M));

// Plinko (16 rows)
console.log("slot", floats(16).filter((x) => x >= 0.5).length);`;

export default function GameRules() {
  return (
    <LegalPage
      slug="game-rules"
      intro={
        <p>
          These rules apply to all games on A2Casino together with the <L to="terms" />. Each game also has its own rules and
          paytable, available inside the game. If those conflict with this page on how a specific game works, the game&apos;s own
          rules apply.
        </p>
      }
      sections={[
        {
          title: "General rules",
          items: [
            <p>Games are provided by third-party studios and by us (&quot;A2 Labs&quot;). Results of third-party games are generated by the provider&apos;s random number generator (RNG), which is tested and certified by {co.testingLab} or another independent laboratory as required by the provider&apos;s licence. <b>The result recorded by the provider is final.</b></p>,
            <p>A bet is placed when it is accepted by our server and the stake has been taken from your balance. Stakes are taken from the real balance first and then from the bonus balance; wins are credited in the same proportion (see the <L to="bonus-terms" />).</p>,
            <p><b>Malfunction voids all pays and plays.</b> If a game or system error affects a round, the bets and wins in that round are void. If a round cannot be completed, the provider may cancel it and the stake is refunded; the bet is shown as &quot;voided&quot; in your history.</p>,
            <p>If you are disconnected during a round, the round is completed on the server according to the game&apos;s rules. Your bet history shows the outcome.</p>,
            <p><b>Maximum win.</b> For A2 Labs (Dice, Crash, Mines and Plinko) the maximum win is <OriginalsMaxWin /> per bet (see section 3): a win above it is paid at the maximum. For third-party games the maximum win is {pending.maxWin}, or the lower limit set in a game&apos;s own rules.</p>,
            <p>Minimum and maximum stakes are shown in each game. Game availability depends on your country: some games and studios are not available in some countries and are hidden there.</p>,
            <p>We may add, change or withdraw games at any time. Unfinished rounds of a withdrawn game are settled or refunded.</p>,
          ],
        },
        {
          title: "Return to player (RTP)",
          lead: (
            <>
              <p>The RTP is the share of all money bet on a game that is paid back to players over a very large number of rounds, as set by the game&apos;s maths. For example, an RTP of 96% means that on average $96 is paid back for every $100 bet. It is a long-term theoretical figure: in any single session you can win more or lose everything you bet.</p>
              <p>The table below is loaded live from our game catalogue, so it always shows the games currently available to you and their published RTP.</p>
            </>
          ),
          after: <GamesRtpTable />,
        },
        {
          title: "A2 Labs: RTP versions and maximum win",
          lead: <p>Our own games can be run at one of several published RTP versions: <b>90%, 92%, 94%, 95%, 96%, 97%, 98% or 99%</b>. The version is chosen per game by the operator and is shown on each game&apos;s page, in the RTP table above and below. In the rules below, <b>R</b> is that RTP as a fraction (for example R = 0.99 for 99%, 0.96 for 96%) and the house edge is 1 − R.</p>,
          items: [
            <p><b>The same for everyone, fixed in advance.</b> The RTP of a game is the same for every player and every bet. It is never adjusted for an individual player, a session, a balance, past results or any other circumstance, and it does not change during play. It can only be changed by an authorised administrator as a configuration of the game; every change is recorded in our audit log.</p>,
            <p><b>A change applies to new bets only.</b> A bet is always settled at the RTP shown when it was placed. A Mines round in progress keeps the RTP and the maximum win it was started with until it ends. Every result, in the game and in your bet history, records the RTP it was played at, and the provably fair verification uses that RTP.</p>,
            <p><b>Maximum win per bet.</b> A single bet in an A2 Original can win at most the amount shown below and on the game page (currently <OriginalsMaxWin /> unless shown otherwise). A win above it is paid at the maximum win; a stake above the maximum win is not accepted. In Mines, the round is cashed out automatically as soon as the payout reaches the maximum win. The maximum win applies to the total payout of the bet, stake included.</p>,
          ],
          after: <OriginalsRtpTable />,
        },
        {
          title: "Dice (A2 Labs)",
          lead: <p>Dice is our own game. You choose a target number; a number from 0.00 to 99.99 is rolled, and you win if the roll is <b>below</b> your target.</p>,
          items: [
            <p><b>Target and chance.</b> The target can be set between 2 and 98. The chance of winning in percent equals the target: a target of 50 wins with a roll of 0.00 to 49.99, which is 5,000 of the 10,000 possible rolls (50%).</p>,
            <p><b>Payout.</b> The payout multiplier is <code>R × 100 / target</code>. A winning bet pays stake × multiplier, rounded down to the cent and up to the maximum win; a losing bet pays nothing. Example at 99% RTP: $1.00 at target 50 pays x1.98, i.e. $1.98; at 96% RTP it pays x1.92.</p>,
            <p><b>House edge and RTP.</b> The chance of winning is target / 100, so the expected return is target / 100 × R × 100 / target = <b>R</b> at every target: the RTP is R and the house edge is 1 − R (1% at 99% RTP).</p>,
            <p><b>Stakes.</b> The minimum bet is {RULES.minDiceBet}. The maximum bet is {pending.maxDiceBet}, and is never more than the maximum win per bet or your available balance.</p>,
            <p>While you have an active bonus, the maximum bet of the <L to="bonus-terms" /> applies (normally $5.00 per roll). Bets on Dice count only partly towards bonus wagering (see the wagering contribution table in the <L to="bonus-terms" />); real-money bets count in full towards VIP points.</p>,
          ],
        },
        {
          title: "Dice: provably fair",
          lead: <p>Every Dice result can be checked by you. Neither you nor we can change a result after the bet, and you can prove it.</p>,
          items: [
            <p><b>One seed pair for all originals.</b> Dice, Crash, Mines and Plinko use the same seed pair and the same nonce, so the nonce goes up by one with every bet in any of them. Each result shows the nonce, the client seed and the server seed hash it was made with. Every game page has a &quot;Verify a result&quot; section that recomputes any result in your browser once the seed pair has been rotated.</p>,
            <p><b>Seeds.</b> You have your own seed pair: a secret <b>server seed</b> (a random 64-character string we generate) and a <b>client seed</b> (random by default; you can choose your own, up to 64 characters). A <b>nonce</b> counts your bets with the current pair: it starts at 0 and goes up by 1 with each bet.</p>,
            <p><b>Commitment.</b> Before you bet, the game shows the SHA-256 hash of the current server seed. Because the hash is published in advance, we cannot change the server seed afterwards without the hash changing.</p>,
            <>
              <p><b>The roll.</b> Each result is calculated as:</p>
              <pre><code>{`HMAC = HMAC-SHA256(key = server seed, message = "client seed:nonce")
roll = (first 4 bytes of HMAC as an unsigned big-endian integer mod 10000) / 100`}</code></pre>
              <p>This gives a roll from 0.00 to 99.99. The server seed is used as text (the characters of the string, not decoded from hex). Taking the remainder of a 32-bit number makes rolls from 0.00 to 72.95 more likely than the others by a negligible amount (about 0.0002% relative).</p>
            </>,
            <p><b>Rotation.</b> When you press &quot;Rotate seed&quot;, the current server seed is revealed, a new server seed is generated and its hash shown, your client seed is set to the one you entered (or a new random one), and the nonce starts again at 0. The game shows the previous server seed so you can verify all bets made with it. Only the most recent previous seed is displayed, so copy it if you want to keep it.</p>,
            <>
              <p><b>How to verify.</b> After rotating, take the revealed server seed and check that its SHA-256 hash matches the hash you saw before betting. Then recompute each roll with your client seed and the nonce of each bet (shown in the game&apos;s results list) and compare it with the result you got. For example, in Node.js:</p>
              <pre><code>{nodeCheck}</code></pre>
              <p>Or in Python:</p>
              <pre><code>{pyCheck}</code></pre>
            </>,
            <p>If a result does not match, contact {co.supportEmail} with the seeds, nonce and the time of the bet.</p>,
          ],
        },
        {
          title: "Crash (A2 Labs)",
          lead: <p>Crash is a single-player game: you choose an <b>auto cash-out</b> multiplier before the bet. A multiplier starts at 1.00x and rises until it &quot;crashes&quot;. If the crash point reaches your auto cash-out, you win your stake × your auto cash-out; otherwise you lose the stake.</p>,
          items: [
            <p><b>Settlement.</b> The crash point is decided by the provably fair seeds when the bet is placed and the bet settles immediately. The rising multiplier on screen is an animation of that result; closing the page does not change it. There is no manual cash-out: only the auto cash-out you set counts.</p>,
            <p><b>Auto cash-out</b> can be set from 1.01x to 1000.00x in steps of 0.01x. The payout is stake × auto cash-out, rounded down to the cent.</p>,
            <>
              <p><b>Crash point.</b></p>
              <pre><code>{`HMAC = HMAC-SHA256(key = server seed, message = "client seed:nonce")
H = the first 52 bits of HMAC (first 13 hex characters), E = 2^52
crash point = max(1.00, floor(RTP × E / (E − H)) / 100)      (RTP in percent, e.g. 99)`}</code></pre>
              <p>With this formula the chance that the crash point reaches a multiplier m is R ÷ m (at 99% RTP: 49.5% for 2.00x, 9.9% for 10.00x; at 96%: 48% and 9.6%). A share 1 − R ÷ 1.01 of rounds ends at 1.00x (about 1.98% at 99% RTP).</p>
            </>,
            <p><b>House edge and RTP.</b> The expected return is m × R ÷ m = <b>R</b> for every auto cash-out: the RTP is R and the house edge is 1 − R. The payout is capped at the maximum win per bet.</p>,
            <p><b>Stakes.</b> The minimum bet is {RULES.minDiceBet}. While a bonus is active its maximum bet applies (normally $5.00 per bet); Crash counts 10% towards bonus wagering by default (see the <L to="bonus-terms" />).</p>,
          ],
        },
        {
          title: "Mines (A2 Labs)",
          lead: <p>Mines is played on a 5 × 5 board of 25 tiles. You choose 1 to 24 mines and place your bet; the mines are hidden on the board. Reveal tiles one at a time: each safe tile (a gem) raises the multiplier, a mine ends the round and the stake is lost. You can cash out after any safe tile.</p>,
          items: [
            <>
              <p><b>Multiplier.</b> After n safe tiles with M mines the multiplier is:</p>
              <pre><code>{`multiplier = R × C(25, n) / C(25 − M, n)`}</code></pre>
              <p>C(a, b) is the number of ways to choose b tiles out of a. Example at 99% RTP: 3 mines, 2 gems = 0.99 × 300 / 231 = 1.2857x; 24 mines, 1 gem = 24.75x (24x at 96%). The payout is stake × multiplier, rounded down to the cent, up to the maximum win per bet. When every safe tile is revealed, or the payout reaches the maximum win, the round is cashed out automatically.</p>
            </>,
            <p><b>House edge and RTP.</b> The chance of finding n safe tiles in a row is C(25 − M, n) / C(25, n), so cashing out at any point returns <b>R</b> on average: the RTP is R and the house edge is 1 − R for every number of mines. The theoretical multipliers with many mines and gems are very large (millions), so the maximum win per bet effectively limits them; because of the cap, the return of a strategy whose payout would exceed it is lower than R.</p>,
            <>
              <p><b>Mine positions.</b> Tiles are numbered 0 to 24, row by row (tile = row × 5 + column). The mines are fixed when the bet is placed:</p>
              <pre><code>{`float stream: HMAC-SHA256(server seed, "client seed:nonce:cursor") for cursor = 0, 1, 2, …
each 4 bytes of an HMAC → unsigned big-endian integer / 2^32 (8 floats per HMAC)
tiles = [0, 1, …, 24]
for i = 24 down to 1: j = floor(next float × (i + 1)); swap tiles[i] and tiles[j]
mines = the first M tiles`}</code></pre>
            </>,
            <p><b>Open rounds.</b> You can have one Mines round at a time. It is kept if you close or reload the page and continues where you left off. A round left open for 24 hours is cashed out automatically at its current multiplier (with no tile revealed, the stake is returned). While a round is open the seed pair cannot be rotated, because rotating reveals the server seed. When a round ends, all mine positions are shown. During a time-out or self-exclusion you cannot start a round, but you can finish an open one.</p>,
            <p><b>Stakes.</b> The minimum bet is {RULES.minDiceBet}. While a bonus is active its maximum bet applies to the stake; Mines counts 10% towards bonus wagering by default.</p>,
          ],
        },
        {
          title: "Plinko (A2 Labs)",
          lead: <p>A ball is dropped from the top of a triangle of pegs with 8, 12 or 16 rows. At each row it bounces left or right with equal chance and lands in one of the slots at the bottom (rows + 1 slots). Each slot pays a multiplier of your stake, which depends on the number of rows and the risk level (low, medium or high).</p>,
          items: [
            <>
              <p><b>Path.</b> One float per row from the same stream as Mines:</p>
              <pre><code>{`float stream: HMAC-SHA256(server seed, "client seed:nonce:cursor"), 4 bytes / 2^32 per float
row k: float ≥ 0.5 → right, otherwise left
slot = number of right bounces (0 = far left)`}</code></pre>
              <p>The chance of landing in slot k is C(rows, k) / 2^rows, so the middle slots are hit most often.</p>
            </>,
            <p><b>Payout tables and RTP.</b> The payout is stake × the slot&apos;s multiplier, rounded down to the cent, up to the maximum win per bet. The RTP of a table is the sum over all slots of C(rows, k) / 2^rows × multiplier. Each RTP version has its own tables: the 99% tables return between 98.9% and 99.2%; the tables of the other versions are the 99% tables scaled to the version&apos;s RTP and rounded to 0.01x, then adjusted by 0.01x on matching slots until the table returns the version&apos;s RTP (within 0.01%), keeping the same shape. The tables below, for the RTP Plinko runs at now, are loaded live from the game server; the in-game verifier rebuilds the tables of any version in your browser.</p>,
            <p><b>Stakes.</b> The minimum bet is {RULES.minDiceBet}. While a bonus is active its maximum bet applies; Plinko counts 10% towards bonus wagering by default.</p>,
          ],
          after: <PlinkoTablesLive />,
        },
        {
          title: "Verifying Crash, Mines and Plinko",
          items: [
            <p>Use the &quot;Verify a result&quot; section on the game page (choose the RTP the bet was played at, shown with the result), or recompute the results yourself after rotating the seed pair, for example in Node.js:</p>,
            <pre><code>{nodeOriginals}</code></pre>,
          ],
        },
      ]}
    />
  );
}
