import LegalPage, { L, co, legalMetadata, pending } from "@/components/LegalPage";
import { GamesRtpTable } from "@/components/LegalLive";
import { RULES } from "@/lib/company";

export const metadata = legalMetadata("game-rules");

const nodeCheck = `const crypto = require("crypto");

const serverSeed = "...";  // revealed when you rotate the seed
const clientSeed = "...";  // your client seed for those bets
const nonce = 0;           // the bet's nonce

// 1. The revealed seed must match the hash shown before you bet
console.log(crypto.createHash("sha256").update(serverSeed).digest("hex"));

// 2. Recompute the roll
const h = crypto.createHmac("sha256", serverSeed).update(clientSeed + ":" + nonce).digest();
console.log(((h.readUInt32BE(0) % 10000) / 100).toFixed(2));`;

const pyCheck = `import hashlib, hmac

server_seed, client_seed, nonce = "...", "...", 0
print(hashlib.sha256(server_seed.encode()).hexdigest())
h = hmac.new(server_seed.encode(), f"{client_seed}:{nonce}".encode(), hashlib.sha256).digest()
print("%.2f" % (int.from_bytes(h[:4], "big") % 10000 / 100))`;

export default function GameRules() {
  return (
    <LegalPage
      slug="game-rules"
      intro={
        <p>
          These rules apply to all games on A2Casino together with the <L to="terms" />. Each game also has its own rules and
          paytable, available inside the game. If those conflict with this page on how a specific game works, the game&apos;s own
          rules apply.
        </p>
      }
      sections={[
        {
          title: "General rules",
          items: [
            <p>Games are provided by third-party studios and by us (&quot;A2 Originals&quot;). Results of third-party games are generated by the provider&apos;s random number generator (RNG), which is tested and certified by {co.testingLab} or another independent laboratory as required by the provider&apos;s licence. <b>The result recorded by the provider is final.</b></p>,
            <p>A bet is placed when it is accepted by our server and the stake has been taken from your balance. Stakes are taken from the real balance first and then from the bonus balance; wins are credited in the same proportion (see the <L to="bonus-terms" />).</p>,
            <p><b>Malfunction voids all pays and plays.</b> If a game or system error affects a round, the bets and wins in that round are void. If a round cannot be completed, the provider may cancel it and the stake is refunded; the bet is shown as &quot;voided&quot; in your history.</p>,
            <p>If you are disconnected during a round, the round is completed on the server according to the game&apos;s rules. Your bet history shows the outcome.</p>,
            <p>The maximum win is {pending.maxWin}, or the lower limit set in a game&apos;s own rules.</p>,
            <p>Minimum and maximum stakes are shown in each game. Game availability depends on your country: some games and studios are not available in some countries and are hidden there.</p>,
            <p>We may add, change or withdraw games at any time. Unfinished rounds of a withdrawn game are settled or refunded.</p>,
          ],
        },
        {
          title: "Return to player (RTP)",
          lead: (
            <>
              <p>The RTP is the share of all money bet on a game that is paid back to players over a very large number of rounds, as set by the game&apos;s maths. For example, an RTP of 96% means that on average $96 is paid back for every $100 bet. It is a long-term theoretical figure: in any single session you can win more or lose everything you bet.</p>
              <p>The table below is loaded live from our game catalogue, so it always shows the games currently available to you and their published RTP.</p>
            </>
          ),
          after: <GamesRtpTable />,
        },
        {
          title: "Dice (A2 Originals)",
          lead: <p>Dice is our own game. You choose a target number; a number from 0.00 to 99.99 is rolled, and you win if the roll is <b>below</b> your target.</p>,
          items: [
            <p><b>Target and chance.</b> The target can be set between 2 and 98. The chance of winning in percent equals the target: a target of 50 wins with a roll of 0.00 to 49.99, which is 5,000 of the 10,000 possible rolls (50%).</p>,
            <p><b>Payout.</b> The payout multiplier is <code>99 / target</code>. A winning bet pays stake × multiplier, rounded down to the cent; a losing bet pays nothing. Example: $1.00 at target 50 pays x1.98, i.e. $1.98.</p>,
            <p><b>House edge and RTP.</b> Because the multiplier is 99 / target, the expected return is 99% at every target: the house edge is 1% and the RTP is 99%.</p>,
            <p><b>Stakes.</b> The minimum bet is {RULES.minDiceBet}. The maximum bet is {pending.maxDiceBet}, and is never more than your available balance.</p>,
            <p>While you have an active bonus, the maximum bet of the <L to="bonus-terms" /> applies (normally $5.00 per roll). Bets on Dice count only partly towards bonus wagering (see the wagering contribution table in the <L to="bonus-terms" />); real-money bets count in full towards VIP points.</p>,
          ],
        },
        {
          title: "Dice: provably fair",
          lead: <p>Every Dice result can be checked by you. Neither you nor we can change a result after the bet, and you can prove it.</p>,
          items: [
            <p><b>Seeds.</b> You have your own seed pair: a secret <b>server seed</b> (a random 64-character string we generate) and a <b>client seed</b> (random by default; you can choose your own, up to 64 characters). A <b>nonce</b> counts your bets with the current pair: it starts at 0 and goes up by 1 with each bet.</p>,
            <p><b>Commitment.</b> Before you bet, the game shows the SHA-256 hash of the current server seed. Because the hash is published in advance, we cannot change the server seed afterwards without the hash changing.</p>,
            <>
              <p><b>The roll.</b> Each result is calculated as:</p>
              <pre><code>{`HMAC = HMAC-SHA256(key = server seed, message = "client seed:nonce")
roll = (first 4 bytes of HMAC as an unsigned big-endian integer mod 10000) / 100`}</code></pre>
              <p>This gives a roll from 0.00 to 99.99. The server seed is used as text (the characters of the string, not decoded from hex). Taking the remainder of a 32-bit number makes rolls from 0.00 to 72.95 more likely than the others by a negligible amount (about 0.0002% relative).</p>
            </>,
            <p><b>Rotation.</b> When you press &quot;Rotate seed&quot;, the current server seed is revealed, a new server seed is generated and its hash shown, your client seed is set to the one you entered (or a new random one), and the nonce starts again at 0. The game shows the previous server seed so you can verify all bets made with it. Only the most recent previous seed is displayed, so copy it if you want to keep it.</p>,
            <>
              <p><b>How to verify.</b> After rotating, take the revealed server seed and check that its SHA-256 hash matches the hash you saw before betting. Then recompute each roll with your client seed and the nonce of each bet (shown in the game&apos;s results list) and compare it with the result you got. For example, in Node.js:</p>
              <pre><code>{nodeCheck}</code></pre>
              <p>Or in Python:</p>
              <pre><code>{pyCheck}</code></pre>
            </>,
            <p>If a result does not match, contact {co.supportEmail} with the seeds, nonce and the time of the bet.</p>,
          ],
        },
      ]}
    />
  );
}
