import LegalPage, { L, co, legalMetadata, pending } from "@/components/LegalPage";
import { GamesRtpTable, PlinkoTablesLive } from "@/components/LegalLive";
import { RULES } from "@/lib/company";

export const metadata = legalMetadata("game-rules");

const nodeCheck = `const crypto = require("crypto");

const serverSeed = "...";  // revealed when you rotate the seed
const clientSeed = "...";  // your client seed for those bets
const nonce = 0;           // the bet's nonce

// 1. The revealed seed must match the hash shown before you bet
console.log(crypto.createHash("sha256").update(serverSeed).digest("hex"));

// 2. Recompute the roll
const h = crypto.createHmac("sha256", serverSeed).update(clientSeed + ":" + nonce).digest();
console.log(((h.readUInt32BE(0) % 10000) / 100).toFixed(2));`;

const pyCheck = `import hashlib, hmac

server_seed, client_seed, nonce = "...", "...", 0
print(hashlib.sha256(server_seed.encode()).hexdigest())
h = hmac.new(server_seed.encode(), f"{client_seed}:{nonce}".encode(), hashlib.sha256).digest()
print("%.2f" % (int.from_bytes(h[:4], "big") % 10000 / 100))`;

const nodeOriginals = `const crypto = require("crypto");
const hmac = (key, msg) => crypto.createHmac("sha256", key).update(msg).digest();
const serverSeed = "...", clientSeed = "...", nonce = 0;

// Crash point
const H = BigInt("0x" + hmac(serverSeed, clientSeed + ":" + nonce).toString("hex").slice(0, 13));
const E = 2n ** 52n;
let c = (99n * E) / (E - H);
console.log("crash", Number(c < 100n ? 100n : c) / 100);

// Float stream for Mines and Plinko
function floats(n) {
  const out = [];
  for (let cursor = 0; out.length < n; cursor++) {
    const h = hmac(serverSeed, clientSeed + ":" + nonce + ":" + cursor);
    for (let i = 0; i < 32 && out.length < n; i += 4) out.push(h.readUInt32BE(i) / 2 ** 32);
  }
  return out;
}

// Mines (M mines)
const M = 3, tiles = [...Array(25).keys()], f = floats(24);
for (let k = 0, i = 24; i >= 1; k++, i--) { const j = Math.floor(f[k] * (i + 1)); [tiles[i], tiles[j]] = [tiles[j], tiles[i]]; }
console.log("mines", tiles.slice(0, M));

// Plinko (16 rows)
console.log("slot", floats(16).filter((x) => x >= 0.5).length);`;

export default function GameRules() {
  return (
    <LegalPage
      slug="game-rules"
      intro={
        <p>
          These rules apply to all games on A2Casino together with the <L to="terms" />. Each game also has its own rules and
          paytable, available inside the game. If those conflict with this page on how a specific game works, the game&apos;s own
          rules apply.
        </p>
      }
      sections={[
        {
          title: "General rules",
          items: [
            <p>Games are provided by third-party studios and by us (&quot;A2 Originals&quot;). Results of third-party games are generated by the provider&apos;s random number generator (RNG), which is tested and certified by {co.testingLab} or another independent laboratory as required by the provider&apos;s licence. <b>The result recorded by the provider is final.</b></p>,
            <p>A bet is placed when it is accepted by our server and the stake has been taken from your balance. Stakes are taken from the real balance first and then from the bonus balance; wins are credited in the same proportion (see the <L to="bonus-terms" />).</p>,
            <p><b>Malfunction voids all pays and plays.</b> If a game or system error affects a round, the bets and wins in that round are void. If a round cannot be completed, the provider may cancel it and the stake is refunded; the bet is shown as &quot;voided&quot; in your history.</p>,
            <p>If you are disconnected during a round, the round is completed on the server according to the game&apos;s rules. Your bet history shows the outcome.</p>,
            <p>The maximum win is {pending.maxWin}, or the lower limit set in a game&apos;s own rules.</p>,
            <p>Minimum and maximum stakes are shown in each game. Game availability depends on your country: some games and studios are not available in some countries and are hidden there.</p>,
            <p>We may add, change or withdraw games at any time. Unfinished rounds of a withdrawn game are settled or refunded.</p>,
          ],
        },
        {
          title: "Return to player (RTP)",
          lead: (
            <>
              <p>The RTP is the share of all money bet on a game that is paid back to players over a very large number of rounds, as set by the game&apos;s maths. For example, an RTP of 96% means that on average $96 is paid back for every $100 bet. It is a long-term theoretical figure: in any single session you can win more or lose everything you bet.</p>
              <p>The table below is loaded live from our game catalogue, so it always shows the games currently available to you and their published RTP.</p>
            </>
          ),
          after: <GamesRtpTable />,
        },
        {
          title: "Dice (A2 Originals)",
          lead: <p>Dice is our own game. You choose a target number; a number from 0.00 to 99.99 is rolled, and you win if the roll is <b>below</b> your target.</p>,
          items: [
            <p><b>Target and chance.</b> The target can be set between 2 and 98. The chance of winning in percent equals the target: a target of 50 wins with a roll of 0.00 to 49.99, which is 5,000 of the 10,000 possible rolls (50%).</p>,
            <p><b>Payout.</b> The payout multiplier is <code>99 / target</code>. A winning bet pays stake × multiplier, rounded down to the cent; a losing bet pays nothing. Example: $1.00 at target 50 pays x1.98, i.e. $1.98.</p>,
            <p><b>House edge and RTP.</b> Because the multiplier is 99 / target, the expected return is 99% at every target: the house edge is 1% and the RTP is 99%.</p>,
            <p><b>Stakes.</b> The minimum bet is {RULES.minDiceBet}. The maximum bet is {pending.maxDiceBet}, and is never more than your available balance.</p>,
            <p>While you have an active bonus, the maximum bet of the <L to="bonus-terms" /> applies (normally $5.00 per roll). Bets on Dice count only partly towards bonus wagering (see the wagering contribution table in the <L to="bonus-terms" />); real-money bets count in full towards VIP points.</p>,
          ],
        },
        {
          title: "Dice: provably fair",
          lead: <p>Every Dice result can be checked by you. Neither you nor we can change a result after the bet, and you can prove it.</p>,
          items: [
            <p><b>One seed pair for all originals.</b> Dice, Crash, Mines and Plinko use the same seed pair and the same nonce, so the nonce goes up by one with every bet in any of them. Each result shows the nonce, the client seed and the server seed hash it was made with. Every game page has a &quot;Verify a result&quot; section that recomputes any result in your browser once the seed pair has been rotated.</p>,
            <p><b>Seeds.</b> You have your own seed pair: a secret <b>server seed</b> (a random 64-character string we generate) and a <b>client seed</b> (random by default; you can choose your own, up to 64 characters). A <b>nonce</b> counts your bets with the current pair: it starts at 0 and goes up by 1 with each bet.</p>,
            <p><b>Commitment.</b> Before you bet, the game shows the SHA-256 hash of the current server seed. Because the hash is published in advance, we cannot change the server seed afterwards without the hash changing.</p>,
            <>
              <p><b>The roll.</b> Each result is calculated as:</p>
              <pre><code>{`HMAC = HMAC-SHA256(key = server seed, message = "client seed:nonce")
roll = (first 4 bytes of HMAC as an unsigned big-endian integer mod 10000) / 100`}</code></pre>
              <p>This gives a roll from 0.00 to 99.99. The server seed is used as text (the characters of the string, not decoded from hex). Taking the remainder of a 32-bit number makes rolls from 0.00 to 72.95 more likely than the others by a negligible amount (about 0.0002% relative).</p>
            </>,
            <p><b>Rotation.</b> When you press &quot;Rotate seed&quot;, the current server seed is revealed, a new server seed is generated and its hash shown, your client seed is set to the one you entered (or a new random one), and the nonce starts again at 0. The game shows the previous server seed so you can verify all bets made with it. Only the most recent previous seed is displayed, so copy it if you want to keep it.</p>,
            <>
              <p><b>How to verify.</b> After rotating, take the revealed server seed and check that its SHA-256 hash matches the hash you saw before betting. Then recompute each roll with your client seed and the nonce of each bet (shown in the game&apos;s results list) and compare it with the result you got. For example, in Node.js:</p>
              <pre><code>{nodeCheck}</code></pre>
              <p>Or in Python:</p>
              <pre><code>{pyCheck}</code></pre>
            </>,
            <p>If a result does not match, contact {co.supportEmail} with the seeds, nonce and the time of the bet.</p>,
          ],
        },
        {
          title: "Crash (A2 Originals)",
          lead: <p>Crash is a single-player game: you choose an <b>auto cash-out</b> multiplier before the bet. A multiplier starts at 1.00x and rises until it &quot;crashes&quot;. If the crash point reaches your auto cash-out, you win your stake × your auto cash-out; otherwise you lose the stake.</p>,
          items: [
            <p><b>Settlement.</b> The crash point is decided by the provably fair seeds when the bet is placed and the bet settles immediately. The rising multiplier on screen is an animation of that result; closing the page does not change it. There is no manual cash-out: only the auto cash-out you set counts.</p>,
            <p><b>Auto cash-out</b> can be set from 1.01x to 1000.00x in steps of 0.01x. The payout is stake × auto cash-out, rounded down to the cent.</p>,
            <>
              <p><b>Crash point.</b></p>
              <pre><code>{`HMAC = HMAC-SHA256(key = server seed, message = "client seed:nonce")
H = the first 52 bits of HMAC (first 13 hex characters), E = 2^52
crash point = max(1.00, floor(99 × E / (E − H)) / 100)`}</code></pre>
              <p>With this formula the chance that the crash point reaches a multiplier m is 99% ÷ m (for example 49.5% for 2.00x, 9.9% for 10.00x). About 1.98% of rounds end at 1.00x.</p>
            </>,
            <p><b>House edge and RTP.</b> The expected return is m × 0.99 ÷ m = <b>99%</b> for every auto cash-out: the house edge is 1% and the RTP is 99%.</p>,
            <p><b>Stakes.</b> The minimum bet is {RULES.minDiceBet}. While a bonus is active its maximum bet applies (normally $5.00 per bet); Crash counts 10% towards bonus wagering by default (see the <L to="bonus-terms" />).</p>,
          ],
        },
        {
          title: "Mines (A2 Originals)",
          lead: <p>Mines is played on a 5 × 5 board of 25 tiles. You choose 1 to 24 mines and place your bet; the mines are hidden on the board. Reveal tiles one at a time: each safe tile (a gem) raises the multiplier, a mine ends the round and the stake is lost. You can cash out after any safe tile.</p>,
          items: [
            <>
              <p><b>Multiplier.</b> After n safe tiles with M mines the multiplier is:</p>
              <pre><code>{`multiplier = 0.99 × C(25, n) / C(25 − M, n)`}</code></pre>
              <p>C(a, b) is the number of ways to choose b tiles out of a. Example: 3 mines, 2 gems = 0.99 × 300 / 231 = 1.2857x; 24 mines, 1 gem = 24.75x. The payout is stake × multiplier, rounded down to the cent. When every safe tile is revealed the round is cashed out automatically.</p>
            </>,
            <p><b>House edge and RTP.</b> The chance of finding n safe tiles in a row is C(25 − M, n) / C(25, n), so cashing out at any point returns <b>99%</b> on average: the house edge is 1% and the RTP is 99% for every number of mines.</p>,
            <>
              <p><b>Mine positions.</b> Tiles are numbered 0 to 24, row by row (tile = row × 5 + column). The mines are fixed when the bet is placed:</p>
              <pre><code>{`float stream: HMAC-SHA256(server seed, "client seed:nonce:cursor") for cursor = 0, 1, 2, …
each 4 bytes of an HMAC → unsigned big-endian integer / 2^32 (8 floats per HMAC)
tiles = [0, 1, …, 24]
for i = 24 down to 1: j = floor(next float × (i + 1)); swap tiles[i] and tiles[j]
mines = the first M tiles`}</code></pre>
            </>,
            <p><b>Open rounds.</b> You can have one Mines round at a time. It is kept if you close or reload the page and continues where you left off. A round left open for 24 hours is cashed out automatically at its current multiplier (with no tile revealed, the stake is returned). While a round is open the seed pair cannot be rotated, because rotating reveals the server seed. When a round ends, all mine positions are shown. During a time-out or self-exclusion you cannot start a round, but you can finish an open one.</p>,
            <p><b>Stakes.</b> The minimum bet is {RULES.minDiceBet}. While a bonus is active its maximum bet applies to the stake; Mines counts 10% towards bonus wagering by default.</p>,
          ],
        },
        {
          title: "Plinko (A2 Originals)",
          lead: <p>A ball is dropped from the top of a triangle of pegs with 8, 12 or 16 rows. At each row it bounces left or right with equal chance and lands in one of the slots at the bottom (rows + 1 slots). Each slot pays a multiplier of your stake, which depends on the number of rows and the risk level (low, medium or high).</p>,
          items: [
            <>
              <p><b>Path.</b> One float per row from the same stream as Mines:</p>
              <pre><code>{`float stream: HMAC-SHA256(server seed, "client seed:nonce:cursor"), 4 bytes / 2^32 per float
row k: float ≥ 0.5 → right, otherwise left
slot = number of right bounces (0 = far left)`}</code></pre>
              <p>The chance of landing in slot k is C(rows, k) / 2^rows, so the middle slots are hit most often.</p>
            </>,
            <p><b>Payout tables and RTP.</b> The payout is stake × the slot&apos;s multiplier, rounded down to the cent. The RTP of a table is the sum over all slots of C(rows, k) / 2^rows × multiplier; every table returns between 98.9% and 99.2% (house edge about 1%). The tables below are loaded live from the game server.</p>,
            <p><b>Stakes.</b> The minimum bet is {RULES.minDiceBet}. While a bonus is active its maximum bet applies; Plinko counts 10% towards bonus wagering by default.</p>,
          ],
          after: <PlinkoTablesLive />,
        },
        {
          title: "Verifying Crash, Mines and Plinko",
          items: [
            <p>Use the &quot;Verify a result&quot; section on the game page, or recompute the results yourself after rotating the seed pair, for example in Node.js:</p>,
            <pre><code>{nodeOriginals}</code></pre>,
          ],
        },
      ]}
    />
  );
}
